---
name: build
run-name: build ${{  github.ref_name }}

on:
  push:
    branches: [main, "REL-*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.11.0
        continue-on-error: true # for act
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
          server-id: vpro-ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
      - name: Build and deploy with Maven 
        run:  mvn -ntp  -B -P"deploy,ossrh,npm" -U -fae deploy
        env:
          SONATYPE_USERNAME: vpro
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}   
      - name: Publish to codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          files: "**/target/surefire-reports/*.xml"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.6.1      
        with:
          junit_files: "**/target/surefire-reports/*.xml"
          check_name: Tests results     



